version: '3.5'
services:
    database:
        image: 'mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04'
        ports:
            - '9001:1433'
        environment:
            ACCEPT_EULA: 'Y'
            SA_PASSWORD: 'Dev-Passwd'
